config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :images
  resources :comments
  resources :likes
  resources :posts
  resources :chickens
  resources :conditions
  resources :hatch_chicks
  resources :hatches
  resources :hatcheries
  resources :predators
  resources :breeds

   root 'posts#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
    validates :name, presence: true
end

app/models/chicken.rb
class Chicken < ActiveRecord::Base
  belongs_to :hatch
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :text
end

app/models/condition.rb
class Condition < ActiveRecord::Base
end

app/models/hatch.rb
class Hatch < ActiveRecord::Base
  has_one :posts, as: :postable
  belongs_to :hatchery
  has_many :images, as: :imageable
  accepts_nested_attributes_for :images
end

app/models/hatch_chick.rb
class HatchChick < ActiveRecord::Base
  valides :hatch, presence:true
  belongs_to :hatch
  belongs_to :breed
  enum sex: [:male, :female]
end

app/models/hatchery.rb
class Hatchery < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :image, ImageUploader
    belongs_to :imageable
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :postable, polymorphic: true
end

app/models/predator.rb
class Predator < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/chickens_controller.rb
class ChickensController < ApplicationController
  before_action :set_chicken, only: [:show, :edit, :update, :destroy]

  # GET /chickens
  # GET /chickens.json
  def index
    @chickens = Chicken.all
  end

  # GET /chickens/1
  # GET /chickens/1.json
  def show
  end

  # GET /chickens/new
  def new
    @chicken = Chicken.new
  end

  # GET /chickens/1/edit
  def edit
  end

  # POST /chickens
  # POST /chickens.json
  def create
    @chicken = Chicken.new(chicken_params)

    respond_to do |format|
      if @chicken.save
        format.html { redirect_to @chicken, notice: 'Chicken was successfully created.' }
        format.json { render :show, status: :created, location: @chicken }
      else
        format.html { render :new }
        format.json { render json: @chicken.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chickens/1
  # PATCH/PUT /chickens/1.json
  def update
    respond_to do |format|
      if @chicken.update(chicken_params)
        format.html { redirect_to @chicken, notice: 'Chicken was successfully updated.' }
        format.json { render :show, status: :ok, location: @chicken }
      else
        format.html { render :edit }
        format.json { render json: @chicken.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chickens/1
  # DELETE /chickens/1.json
  def destroy
    @chicken.destroy
    respond_to do |format|
      format.html { redirect_to chickens_url, notice: 'Chicken was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chicken
      @chicken = Chicken.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chicken_params
      params.require(:chicken).permit(:name, :description, :hatch_id)
    end
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/chickens_helper.rb
module ChickensHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/hatches_helper.rb
module HatchesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/predators_helper.rb
module PredatorsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/chickens/_form.html.erb
<%= form_for(@chicken) do |f| %>
  <% if @chicken.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chicken.errors.count, "error") %> prohibited this chicken from being saved:</h2>

      <ul>
      <% @chicken.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :hatch_id %><br>
    <%= f.text_field :hatch_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chickens/edit.html.erb
<h1>Editing Chicken</h1>

<%= render 'form' %>

<%= link_to 'Show', @chicken %> |
<%= link_to 'Back', chickens_path %>

app/views/chickens/index.html.erb
<h1>Comming soon!</h1>
<!--<p id="notice"><%= notice %></p>-->

<!--<h1>Listing Chickens</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Name</th>-->
<!--      <th>Description</th>-->
<!--      <th>Hatch</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @chickens.each do |chicken| %>-->
<!--      <tr>-->
<!--        <td><%= chicken.name %></td>-->
<!--        <td><%= chicken.description %></td>-->
<!--        <td><%= chicken.hatch %></td>-->
<!--        <td><%= link_to 'Show', chicken %></td>-->
<!--        <td><%= link_to 'Edit', edit_chicken_path(chicken) %></td>-->
<!--        <td><%= link_to 'Destroy', chicken, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%= link_to 'New Chicken', new_chicken_path %>-->

app/views/chickens/new.html.erb
<h1>New Chicken</h1>

<%= render 'form' %>

<%= link_to 'Back', chickens_path %>

app/views/chickens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chicken.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @chicken.description %>
</p>

<p>
  <strong>Hatch:</strong>
  <%= @chicken.hatch %>
</p>

<%= link_to 'Edit', edit_chicken_path(@chicken) %> |
<%= link_to 'Back', chickens_path %>