config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :images
  resources :comments
  resources :likes
  resources :posts
  resources :chickens
  resources :conditions
  resources :hatch_chicks
  resources :hatches
  resources :hatcheries
  resources :predators
  resources :breeds

   root 'posts#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
    validates :name, presence: true
end

app/models/chicken.rb
class Chicken < ActiveRecord::Base
  belongs_to :hatch
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :text
end

app/models/condition.rb
class Condition < ActiveRecord::Base
end

app/models/hatch.rb
class Hatch < ActiveRecord::Base
  has_one :posts, as: :postable
  belongs_to :hatchery
  has_many :images, as: :imageable
  accepts_nested_attributes_for :images
end

app/models/hatch_chick.rb
class HatchChick < ActiveRecord::Base
  valides :hatch, presence:true
  belongs_to :hatch
  belongs_to :breed
  enum sex: [:male, :female]
end

app/models/hatchery.rb
class Hatchery < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :image, ImageUploader
    belongs_to :imageable
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :postable, polymorphic: true
end

app/models/predator.rb
class Predator < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/hatcheries_controller.rb
class HatcheriesController < ApplicationController
  before_action :set_hatchery, only: [:show, :edit, :update, :destroy]

  # GET /hatcheries
  # GET /hatcheries.json
  def index
    @hatcheries = Hatchery.all
  end

  # GET /hatcheries/1
  # GET /hatcheries/1.json
  def show
  end

  # GET /hatcheries/new
  def new
    @hatchery = Hatchery.new
  end

  # GET /hatcheries/1/edit
  def edit
  end

  # POST /hatcheries
  # POST /hatcheries.json
  def create
    @hatchery = Hatchery.new(hatchery_params)

    respond_to do |format|
      if @hatchery.save
        format.html { redirect_to @hatchery, notice: 'Hatchery was successfully created.' }
        format.json { render :show, status: :created, location: @hatchery }
      else
        format.html { render :new }
        format.json { render json: @hatchery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hatcheries/1
  # PATCH/PUT /hatcheries/1.json
  def update
    respond_to do |format|
      if @hatchery.update(hatchery_params)
        format.html { redirect_to @hatchery, notice: 'Hatchery was successfully updated.' }
        format.json { render :show, status: :ok, location: @hatchery }
      else
        format.html { render :edit }
        format.json { render json: @hatchery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hatcheries/1
  # DELETE /hatcheries/1.json
  def destroy
    @hatchery.destroy
    respond_to do |format|
      format.html { redirect_to hatcheries_url, notice: 'Hatchery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hatchery
      @hatchery = Hatchery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hatchery_params
      params.require(:hatchery).permit(:name)
    end
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/chickens_helper.rb
module ChickensHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hatcheries_helper.rb
module HatcheriesHelper
end

app/helpers/hatches_helper.rb
module HatchesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/predators_helper.rb
module PredatorsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/hatcheries/_form.html.erb
<%= form_for(@hatchery) do |f| %>
  <% if @hatchery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hatchery.errors.count, "error") %> prohibited this hatchery from being saved:</h2>

      <ul>
      <% @hatchery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hatcheries/edit.html.erb
<h1>Editing Hatchery</h1>

<%= render 'form' %>

<%= link_to 'Show', @hatchery %> |
<%= link_to 'Back', hatcheries_path %>

app/views/hatcheries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hatcheries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hatcheries.each do |hatchery| %>
      <tr>
        <td><%= hatchery.name %></td>
        <td><%= link_to 'Show', hatchery %></td>
        <td><%= link_to 'Edit', edit_hatchery_path(hatchery) %></td>
        <td><%= link_to 'Destroy', hatchery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hatchery', new_hatchery_path %>

app/views/hatcheries/new.html.erb
<h1>New Hatchery</h1>

<%= render 'form' %>

<%= link_to 'Back', hatcheries_path %>

app/views/hatcheries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hatchery.name %>
</p>

<%= link_to 'Edit', edit_hatchery_path(@hatchery) %> |
<%= link_to 'Back', hatcheries_path %>